spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/hexagonal}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: create